### ISSUE TITLE
Database connection 

### ISSUE THREAD

**Issue by Jafetlch** [F34th3R/laravel-docker-dev-environment#2]
Laravel .env config 

```
// docker-compose
environment:
  MYSQL_DATABASE: laravel
  MYSQL_USER: root
  MYSQL_PASSWORD: secret
  MYSQL_ROOT_PASSWORD: secret
  SERVICE_TAGS: dev
  SERVICE_NAME: mysql
```

```
// .env
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=secret
```
